package com.zgty.oarobot.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zgty.oarobot.bean.Staff;
import com.zgty.oarobot.bean.Time;
import com.zgty.oarobot.bean.Account;
import com.zgty.oarobot.bean.Speaking;

import com.zgty.oarobot.bean.StaffDao;
import com.zgty.oarobot.bean.TimeDao;
import com.zgty.oarobot.bean.AccountDao;
import com.zgty.oarobot.bean.SpeakingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig staffDaoConfig;
    private final DaoConfig timeDaoConfig;
    private final DaoConfig accountDaoConfig;
    private final DaoConfig speakingDaoConfig;

    private final StaffDao staffDao;
    private final TimeDao timeDao;
    private final AccountDao accountDao;
    private final SpeakingDao speakingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        staffDaoConfig = daoConfigMap.get(StaffDao.class).clone();
        staffDaoConfig.initIdentityScope(type);

        timeDaoConfig = daoConfigMap.get(TimeDao.class).clone();
        timeDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        speakingDaoConfig = daoConfigMap.get(SpeakingDao.class).clone();
        speakingDaoConfig.initIdentityScope(type);

        staffDao = new StaffDao(staffDaoConfig, this);
        timeDao = new TimeDao(timeDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);
        speakingDao = new SpeakingDao(speakingDaoConfig, this);

        registerDao(Staff.class, staffDao);
        registerDao(Time.class, timeDao);
        registerDao(Account.class, accountDao);
        registerDao(Speaking.class, speakingDao);
    }
    
    public void clear() {
        staffDaoConfig.clearIdentityScope();
        timeDaoConfig.clearIdentityScope();
        accountDaoConfig.clearIdentityScope();
        speakingDaoConfig.clearIdentityScope();
    }

    public StaffDao getStaffDao() {
        return staffDao;
    }

    public TimeDao getTimeDao() {
        return timeDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public SpeakingDao getSpeakingDao() {
        return speakingDao;
    }

}
